### ISSUE TITLE
NPCs not spawning correctly

### ISSUE THREAD

**Issue by Herringway** [Herringway/earthbound#114]
![image](https://user-images.githubusercontent.com/905162/234173354-76177c56-95e4-4a7b-b090-0d37acfaf774.png)
Some entities are missing while approaching the meteor in the beginning of the game. They spawn when moving further upward.

**Comment by Anonymous941** [comment]
This seems to happen much less when Ness isn't in his pajamas

**Comment by Herringway** [comment]
Nope. it was actually relying on map tiles that were loading. the original NPC spawning code would exit early if an uninitialized variable was negative. on the SNES, that happened to be the address of some memory allocated to hold a tile buffer. Since the heap lives at $7E2000, it was never negative, and so it went completely unnoticed. Here, however, it was using a different variable from that function entirely, and I'm not exactly sure which one. It appears it was one that would be interpreted as a negative number pretty often. The fix was simply to disable the check that just happened to never fail on the SNES.
