### ISSUE TITLE
cannot run

### ISSUE THREAD

**Issue by Dalek-Sek** [Herringway/earthbound#115]
after compiling it using dub I attempted to run it and was met with this error 
`rendering.d:136:loadRenderer Can't load SnesDrawFrame!`
I'm aware that this project is not even nearly done but I'm very interested in trying it out.
I'm running the GNU+Linux operating system.

**Comment by Anonymous941** [comment]
I had the same problem, see #83 and #117 for how I fixed the various errors.  This particular problem was fixed by compiling https://github.com/charasyn/libsfcppu and copying `libsfcppu.so` to `/usr/lib`.

**Comment by Dalek-Sek** [comment]
I saw that I tried to compile the library but I always get this when running it 
`Compiling libsfcppu.cpp ...
libsfcppu.cpp:261:1: fatal error: opening dependency file obj/libsfcppu.d: No such file or directory
  261 | }
      | ^
compilation terminated.
make: *** [nall/GNUmakefile:165: obj/libsfcppu.o] Error 1
`

**Comment by Herringway** [comment]
I think you need to create the obj and out directories manually

**Comment by Anonymous941** [comment]
Yes, I had the same issue and that solved it
