### ISSUE TITLE
Window-based HDMA effects render incorrectly

### ISSUE THREAD

**Issue by Herringway** [Herringway/earthbound#128]
Buzz-buzz's appearance (ignore the AUTO and dead ness)
![image](https://github.com/Herringway/earthbound/assets/905162/b60f46b3-1a4f-499f-a175-76ff50b4f620)

**Comment by Herringway** [comment]
Not quite complete.
Attract mode HDMA:
![image](https://github.com/Herringway/earthbound/assets/905162/ed05e2fd-5f45-4510-ae01-ff1c03647cd0)
(note the column of pixels on the far right)
Battle swirls:
![image](https://github.com/Herringway/earthbound/assets/905162/a473ba78-3f06-4bbd-99f2-d3392b423c01)

with the updated HDMA implementation, the HDMAWrite lists produced appear to be identical to what emulators produce... could this be an issue with libsfcppu? @charasyn

**Comment by charasyn** [comment]
Could you get HDMA and register dumps for these two examples?
________________________________

**Comment by Herringway** [comment]
Sure. here's every single frame
[hdma.zip](https://github.com/Herringway/earthbound/files/11702698/hdma.zip)

**Comment by charasyn** [comment]
By manual inspection of the data with a hex editor, it looks like the HDMA tables are encoding exactly what shows up on screen. I'll try to take a look tomorrow.

**Comment by Herringway** [comment]
the HDMA tables for the swirls come directly from the ROM unmodified, and I've got one frame in the new HDMA unittests. those test cases were verified against mesen's HDMA implementation, so unless I'm misunderstanding something about how libsfcppu handles the HDMAWrite entries, libsfcppu is what I'm suspicious of right now.
