### ISSUE TITLE
Dump > Save doesn't work

### ISSUE THREAD

**Issue by Anonymous941** [Herringway/earthbound#136]
When selecting Save in debug mode, the game doesn't actually save.

**Comment by Herringway** [comment]
Correct. that option creates a save.yaml file for easier reading.

**Comment by Anonymous941** [comment]
Can there be an option or a debug key for saving as well?  I made one a while back to call `saveCurrentGame` with `extra3`, but it's for a much older version

**Comment by Herringway** [comment]
Sure, why not
