### ISSUE TITLE
"license": "proprietary"?

### ISSUE THREAD

**Issue by Anonymous941** [Herringway/earthbound#166]
In dub.json, the license is listed as "proprietary".  Is this referring to EarthBound itself or the project?

**Comment by Herringway** [comment]
earthbound itself. as for the rest of the project... it won't really matter a whole lot in the future, but I'm not ready to share details on that just yet.

**Comment by Anonymous941** [comment]
> it won't really matter a whole lot in the future, but I'm not ready to share details on that just yet.

Are you referring to a future project that will have an open source license?
