### ISSUE TITLE
Add instant text speed option to file menu

### ISSUE THREAD

**Issue by tolmar** [Herringway/earthbound#33]
[Enhancement from PK Scramble & Ancient Cave]

Expand the file menu text selection to include instant. Instant text can be implemented in EB by replacing the INC at 0xc10d4e with a NOP, which makes all text speeds go one faster. (Unfortunately I don't have the code pointer handy for this one.)

**Comment by Herringway** [comment]
we have the luxury of being able to implement this as a 4th option, I think

**Comment by tolmar** [comment]
The PK Scramble version has 5 options! I also added "Potato" which is even slower than slow.

**Comment by tolmar** [comment]
There's also a common request to have text speeds between instant and fast, or between fast and medium. This isn't possible with the current system, where text speeds are just a number of frames to wait between printing letters, but a different system isn't so hard.

**Comment by tolmar** [comment]
The instant text patch (0xc10d4e = NOP) is equivalent to removing the +1 from this line: https://github.com/Herringway/earthbound/blob/b43939035e2a82afd16e3fd4abdb2f3bfb46e4bb/source/earthbound/bank04.d#L1691
