### ISSUE TITLE
Battle background HDMA tables are bogus

### ISSUE THREAD

**Issue by Herringway** [Herringway/earthbound#55]
They will need to be fixed in order to properly distort the backgrounds. I'm not sure what's wrong with them yet.

**Comment by charasyn** [comment]
I found a lead. If you battle a Coil Snake and use debug mode to change "Ripple amplitude" from 8192 to 20, it appears to render more-or-less correctly:
![image](https://github.com/Herringway/earthbound/assets/6129909/7838ec8d-740b-435b-838c-3aa772ee9c2d)

**Comment by Herringway** [comment]
the code that generates these tables is awful handwritten assembly, so I wouldn't be surprised if I made some big mistakes while porting it

**Comment by Herringway** [comment]
Partially fixed by 0d0d94b3. We're not producing accurate results yet, but it's at least not a corrupt mess.
