### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by Anonymous941** [Herringway/earthbound#83]
**Edit:**
I'm trying to contribute to the project but need to build it first.  I've figured out that I needed to use the provided `ebbinex.yml`.  So here are the steps I've done:

1. Compile ebbinex and place the binary in this repo's directory along with the EarthBound.sfc ROM.
2. Extract the resources: `./ebbinex ebbinex.yml EarthBound.sfc`
3. Build the project: `dub build :sdl`
4. Attempt to run the binary: `sdl/earthbound_sdl`

Now I get the error:

```plain
2023-04-19T09:48:39.721 [info] rendering.d:136:loadRenderer Can't load SnesDrawFrame!
```

Is this because it's incomplete?  The issues seem to indicate it can at least run.

**Comment by Anonymous941** [comment]
After some debugging, it appears I need libsfcppu.so, which is part of bSnes.  Should I put its source code somewhere?

**Comment by charasyn** [comment]
I think you have run ebbinex with the data format used with ebsrc. There's a different data format needed for this. I think the .yml file is in this repository.

The code and prebuilt DLL for libsfcppu can be found here: https://github.com/charasyn/libsfcppu/releases/tag/v1.0
________________________________

**Comment by Anonymous941** [comment]
@charasyn

> I think you have run ebbinex with the data format used with ebsrc. There's a different data format needed for this. I think the .yml file is in this repository.

That's correct, I initially had that problem but figured it out.

> The code and prebuilt DLL for libsfcppu can be found here: https://github.com/charasyn/libsfcppu/releases/tag/v1.0

I've managed to get that working now, thank you.  But I'm getting another error:

```plain
2023-04-19T11:34:39.783 [info] rendering.d:143:loadRenderer SnesDrawFrame initialized
2023-04-19T11:34:39.847 [info] rendering.d:148:loadRenderer SDL video subsystem initialized (x11)
2023-04-19T11:34:39.874 [info] rendering.d:192:initializeRenderer SDL renderer subsystem initialized (opengl)
2023-04-19T11:34:39.875 [error] audio.d:17:initAudio Can't load SDL_Mixer!
```

I've made sure that SDL_Mixer was installed on my system and recompiled, but I keep getting this same error.

**Comment by Anonymous941** [comment]
Somehow I've fixed that immediately after posting that comment (despite trying for a long time) using `sudo apt-get install libsdl2-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-gfx-dev`, but now I'm getting an error about `text.cache`:

```plain
2023-04-19T11:41:34.100 [info] rendering.d:143:loadRenderer SnesDrawFrame initialized
2023-04-19T11:41:34.164 [info] rendering.d:148:loadRenderer SDL video subsystem initialized (x11)
2023-04-19T11:41:34.194 [info] rendering.d:192:initializeRenderer SDL renderer subsystem initialized (opengl)
2023-04-19T11:41:34.225 [info] main.d:105:main SDL audio subsystem initialized (pulseaudio)
2023-04-19T11:41:34.273 [info] gamepad.d:26:initializeGamepad SDL game controller subsystem initialized
std.file.FileException@std/file.d(370): text.cache: No such file or directory
??:? @safe bool std.file.cenforce!(bool).cenforce(bool, scope lazy const(char)[], immutable(char)[], ulong) [0x5625954f1458]
??:? @trusted void[] std.file.readImpl(scope const(char)[], scope const(char)*, ulong) [0x5625954ef960]
/usr/include/dmd/phobos/std/file.d:319 @safe void[] std.file.read!(immutable(char)[]).read(immutable(char)[], ulong) [0x562595154a5d]
source/earthbound/text.d:17 void earthbound.text.loadTextCache(immutable(char)[]) [0x56259529e64d]
sdl/source/main.d:154 _Dmain [0x562595244a60]
```

**Comment by Anonymous941** [comment]
I finally have it working.  It turns out the keyboard controls are strange, and I was using the wrong ones.
