### ISSUE TITLE
Unallocated sprites can't be re-allocated

### ISSUE THREAD

**Issue by Anonymous941** [Herringway/earthbound#91]
On the first scene, once you talk to Porky and your mom is supposed to appear, she doesn't appear.  In order to have her appear, you have to enter Porky's house and leave to refresh the scene, probably related to the recent de-allocation fix

**Comment by charasyn** [comment]
Interestingly, not related to the de-allocation fix. No NPCs would spawn when walking up or left, due to the game thinking they were already on-screen. This also affected Lier X. Agerate (which I only noticed after I fixed it)
